name: Publish to PyPI

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required for checkout

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for poetry-dynamic-versioning to work

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run tests
        run: poetry run pytest
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/') # Only publish on tags
        uses: pypa/gh-action-pypi-publish@release/v1
